<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field field-name-lastname">
                <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Lastname') ?></span></label>
                <div style="width: 50%; float:right;">
                    <input name="lastname" type="text" id="lastname"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Lastname') ?>"/>
                </div>
            </div>
            <div class="field field-name-firstname">
                <label class="label" for="firstname"><span><?php /* @escapeNotVerified */ echo __('Firstname') ?></span></label>
                <div style="width: 50%;">
                    <input name="firstname" type="text" id="firstname"
                       placeholder="<?php /* @escapeNotVerified */ echo __('Firstname') ?>"/>
                    <?php //data-validate="{required:true, 'validate-no-empty':true}" ?>
                </div>
            </div>
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
