<?php
/**
 * Created by PhpStorm.
 * User: peter_lelewel
 * Date: 25.09.17
 * Time: 16:50
 */

namespace Flagbit\Inxmail\Test\Unit\Model\Request;

use Flagbit\Inxmail\Model\Request\RequestImports;
use PHPUnit\Framework\TestCase;

class RequestImportsTest extends TestCase
{
    /**
     * @var \Flagbit\Inxmail\Model\Request\RequestImports
     */
    private $requestClient;
    private $requestResponse;
    protected static $testListId = 4;

    private $testCsvFile = array(
        'email;Vorname;Nachname;magentoSubscriberId,magentoSubscriberToken,magentoWebsiteName,magentoWebsiteId,magentoStoreName,magentoStoreViewName,Geburtsdatum,Geschlecht',
        '"peter.lelewel@flagbit.de";"peter";"lelewel";"4";"a36emacqpz96qe8hdyyl8g5qaqv8yyaa";"demo";"1";"Main Website","1";"Default Store View;"1990-02-04","Sir"',
        '"bjoern.meyer@flagbit.de";"bjoern";"meyer";"5";"a36emacqpz96qe8hdyyl8g5qaqv8yyaa";"demo";"1";"Main Website","1";"Default Store View;"1995-01-15","Sir"'
    );

    public function setUp()
    {
        if (!$this->requestClient) {
//            var_dump($this->requestClient);
            $params = $_SERVER;
            $bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
            /** @var \Magento\Framework\App\Http $app */
            $app = $bootstrap->createApplication('Magento\Framework\App\Http');
            unset($app);

            $this->om = \Magento\Framework\App\ObjectManager::getInstance();
            $this->requestClient = (new \Flagbit\Inxmail\Model\Request\RequestFactory($this->om))->create(RequestImports::class, array());
        }
//        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testImportCsv()
    {
        $fileData  = implode(PHP_EOL, $this->testCsvFile);
//var_dump($fileData);
        $this->requestClient->setRequestParam('?listId='.self::$testListId.'&resubscribe=true&truncate=true');
        $this->requestClient->setRequestFile($this->requestClient->getCurlValue('subscriberImport.csv', 'multipart/form-data;charset=UTF-8', $fileData));
        var_dump("bla");
        $response = $this->requestClient->writeRequest();

        var_dump($response);
        //        $result = $this->requestClient->writeRequest();
    }
}
